INSERT INTO todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(1001,'vs45tech','Get AWS Certified',CURRENT_DATE(),false);
INSERT INTO todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(1002,'vs45tech','Get Google Cloud Certified',CURRENT_DATE(),false);
INSERT INTO todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(1003,'vs45tech','Get Golang Certified',CURRENT_DATE(),false);
INSERT INTO todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(1004,'vs45tech','Get React Native Certified',CURRENT_DATE(),false);